x-default-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "300m"
    max-file: '3'

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus-data: null

services:
  evm-service:
    build:
      context: .
      dockerfile: evm-service/Dockerfile
    container_name: evm-service
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network
    logging: *default-logging

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network
    logging: *default-logging
    env_file:
      - .env
    ports:
      - "443:443"  # Exposing HTTPS port
    volumes:
      - ./ssl-certs/cert.crt:/etc/ssl/certs/cert.crt
      - ./ssl-certs/cert.key:/etc/ssl/private/cert.key
    command: uvicorn app.main:app --host 0.0.0.0 --port 443 --ssl-keyfile /etc/ssl/private/cert.key --ssl-certfile /etc/ssl/certs/cert.crt