x-default-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "300m"
    max-file: '3'

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus-data: null

services:
  evm-service:
    build:
      context: .
      dockerfile: evm-service/Dockerfile
    container_name: evm-service
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro