x-default-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "300m"
    max-file: '3'

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus-data:

services:
  evm-service:
    build:
      context: .
      dockerfile: evm-service/Dockerfile
    container_name: evm-service
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network
    logging: *default-logging
    restart: always

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network
    env_file:
      - .env
    logging: *default-logging
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - monitoring_network
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    env_file:
      - .env
    ports:
      - "9090:9090"
    logging: *default-logging
    restart: always