x-default-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "300m"
    max-file: '3'

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus-data: null

services:
  evm-service:
    build:
      context: .
      dockerfile: evm-service/Dockerfile
    container_name: evm-service
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network
    logging: *default-logging

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network
    logging: *default-logging

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring_network
    logging: *default-logging