services:
  ethereum-service:
    build:
      context: .
      dockerfile: ethereum-service/Dockerfile
    container_name: ethereum-service
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge