x-default-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: '10'

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus-data:
  service-logs:

services:
  evm-service:
    build:
      context: .
      dockerfile: evm-service/Dockerfile
    container_name: evm-service
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network
    logging: *default-logging
    restart: always

  solana-service:
    build:
      context: .
      dockerfile: solana-service/Dockerfile
    container_name: solana-service
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network
    logging: *default-logging
    restart: always

  ton-service:
    build:
      context: .
      dockerfile: ton-service/Dockerfile
    container_name: ton-service
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring_network
    logging: *default-logging
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - monitoring_network
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/web.yml:/etc/prometheus/web.yml:ro
    env_file:
      - .env
    ports:
      - "9090:9090"
    logging: *default-logging
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web.yml"
      - "--storage.tsdb.retention.time=90d"
    restart: always