global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ethereum'
    static_configs:
      - targets: ['ethereum-service:8001']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
